<!-- The Grid -->
<div class="w3-row">
	<!-- Left Column -->
	<div class="w3-col m2">
		<div class="w3-card-2 w3-round w3-theme-d2">
			<div class="w3-container w3-padding">
				Recent Posts<br><br>
				<a href="#">Recent Post</a><br>
				<a href="#">Recent Post</a><br>
				<a href="#">Recent Post</a><br>
				<a href="#">Recent Post</a><br>
				<a href="#">Recent Post</a><br>
				<a href="#">Recent Post</a><br>
			</div>
		</div>
	</div>
	<!-- end left column -->
	
	<!-- middle column -->
	<div class="w3-col m7">
		<div class="w3-row-padding">
			<div class="w3-col m12">
				<div class="w3-card-2 w3-round w3-white">
					<div class="w3-container w3-padding">
						<table class="w3-table-all">
							<tr>
								<th>Subject</th>
								<th>Author</th>
								<th>Date</th>
								<th>Replies</th>
							</tr>
							
							<tr>
								<td>Hi</td>
								<td>Jimmy</td>
								<td><?php echo date('F j Y'); ?></td>
								<td>5</td>
							</tr>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end middle column -->
	
	<!-- right column -->
	<div class="w3-col m2">
		<div class="w3-col m12">
			<div class="w3-card-2 w3-round w3-theme-d2">
				<div class="w3-container w3-padding">
					Users Online<br><br>
					Jimmy<br>
					Tim<br>
				</div>
			</div>
		</div>
	</div>
	<!-- end right column -->
	
</div>
<!-- End Grid -->
	