<div class="w3-row-padding">
	<!-- group members currently online col (left) -->
	<div class="w3-col m3" id="left-online">
		<div class="w3-card-2 w3-round w3-theme-d2">
			<div class="w3-container w3-round w3-theme-d2">
				<h6 class="w3-center" style="border-bottom: 1px solid #ddd;">Group Members Online</h6>
				
				<p id="members-online"></p>
				
				<script type="text/javascript">
					$(function() {
						function buildOnlineMemberList() {
							$.ajax({
								type: "GET",
								url: "/members/groups/get-group-members-online",
								dataType: "json"
							}).done(function(msg) {
								if (msg.display_name == "" || msg.display_name == undefined) {
									$('#members-online').html("No group members are online.");
									return false;
								} else {
									var displayNames = msg.display_name.join('<br />');
									$('#members-online').html(displayNames);
								}
							}).fail(function() {
								$('#members-online').html("Error retrieving group list");
							});
						}

						setInterval(function() {
							buildOnlineMemberList();
						}, 5000);

						buildOnlineMemberList();
					});
				</script>
			</div>
		</div>
		
		<br><br>
		
		<div class="w3-card-2 w3-round-w3-theme-d2">
			<div class="w3-container w3-round w3-theme-d2">
				<h6 class="w3-center" style="border-bottom: 1px solid #ddd;">Event Functions</h6>
				
				<p id="event-opts">
					<a href="<?php echo $this->url('members/events', array('action' => 'create-event')); ?>">Create Event</a>
					
					<br>
					
					<a href="<?php echo $this->url('members/events', array('action' => 'view-events')); ?>">View Events</a>
					
					<br>
					
					<a href="<?php echo $this->url('members/events', array('action' => 'index')); ?>">Your Events</a>
					
					<br>
					
					<a href="<?php echo $this->url('members/events', array('action' => 'delete-event')); ?>">Delete Event</a>
				</p>
				
				<script type="text/javascript">
					$('#event-opts a').addClass('w3-hover-text-red');
				</script>
			</div>
		</div>
	</div>
	<!-- end left column -->
	
	
	
	<!-- middle-column -->
	<div class="w3-col m7" id="middle-col">
		<div class="w3-row-padding">
			<div class="w3-col m12">
				<div class="w3-card-2 w3-round w3-white">
					<div class="w3-container w3-padding">
						<h2 class="w3-center w3-white w3-border w3-border-white w3-round-xlarge" style="text-shadow: 1px 1px 0 #000;">
							Create Event
						</h2>
					
						<?php 
						      $this->form->setAttribute('action', $this->url('members/events', array('action' => 'cevent')));
						      
						      $this->form->prepare();
						      
						      echo $this->form()->openTag($this->form);
						?>
						
						<?php 
						
						       echo $this->formRow($this->form->get('event-name'));
						       
						       echo "<div id=\"event-name-error\" class=\"w3-panel w3-red w3-card-2\" style=\"display: none;\">
	                                    <span onclick=\"this.parentElement.style.display='none'\" class=\"w3-button w3-red w3-large w3-right w3-hover-red\">
	                                        &times;
	                                    </span>
	                                ";
						       
						       echo "<p>Event Name cannot be empty.</p>";
						       
						       echo "</div>";
						       
						       echo "<div id=\"event-name-size-error\" class=\"w3-panel w3-red w3-card-2\" style=\"display: none;\">
	                                    <span onclick=\"this.parentElement.style.display='none'\" class=\"w3-button w3-red w3-large w3-right w3-hover-red\">
	                                        &times;
	                                    </span>
	                                ";
						       
						       echo "<p>Event Name size must be between 10 and 100 characters.</p>";
						       
						       echo "</div>";
						       
						       echo "<br>";
						     
						       echo $this->formRow($this->form->get('event-description'));
						       
						       
						       echo "<div id=\"event-desc-error\" class=\"w3-panel w3-red w3-card-2\" style=\"display: none;\">
	                                    <span onclick=\"this.parentElement.style.display='none'\" class=\"w3-button w3-red w3-large w3-right w3-hover-red\">
	                                        &times;
	                                    </span>
	                                ";
						       
						       echo "<p>Event description cannot be empty.</p>";
						       
						       echo "</div>";
						       
						       echo "<div id=\"event-desc-size-error\" class=\"w3-panel w3-red w3-card-2\" style=\"display: none;\">
	                                    <span onclick=\"this.parentElement.style.display='none'\" class=\"w3-button w3-red w3-large w3-right w3-hover-red\">
	                                        &times;
	                                    </span>
	                                ";
						       
						       echo "<p>Event description size must be between 30 and 3000 characters.</p>";
						       
						       echo "</div>";
						       
						       echo "<br>";
						       
						       
						       echo $this->formRow($this->form->get('start-date'));
						       
						       echo "<br>";
						       
						       echo $this->formRow($this->form->get('end-date'));
						       
						      
						       echo $this->formElement($this->form->get('csrf_security'));
						       
						       echo "<br><br>";
						       
						       echo $this->formElement($this->form->get('submit'));
						       
						       echo $this->form()->closeTag();
						?>
					</div>
					
					<script type="text/javascript">
						$('#event-name').on('blur', function() {
							if ($(this).val() == "" || $(this).val() == undefined) {
								$('#event-name-error').css('display', 'block');
								$(this).focus();
								return;
							}

							if ($(this).val().length < 10 || $(this).val().length > 100) {
								$('#event-name-size-error').css('display', 'block');
								$(this).focus();
								return;
							}
						});


						$('#event-description').on('blur', function() {
							if ($(this).val() == "" || $(this).val() == undefined) {
								$('#event-desc-error').css('display', 'block');
								$(this).focus();
								return;
							}

							if ($(this).val().length < 30 || $(this).val().length > 3000) {
								$('#event-desc-size-error').css('display', 'block');
								$(this).focus();
								return;
							}
						});
					</script>
				</div>
			</div>
		</div>
	</div>	
	<!-- end middle column -->
</div>
<!-- end page content -->