<div class="w3-row">
	<div class="w3-col sm-12 w3-center">
		<p class="w3-large">
			<?php echo $this->flashMessenger()
			           ->setMessageOpenFormat('<div%s<p>')
			           ->setMessageSeparatorString('</p><p>')
			           ->setMessageCloseString('</p></div>')
			           ->render('error'); ?>
			<br>
			<a href="<?php echo $this->url('home/register', array('action' => 'index')); ?>">Back To Registration Page</a>
		</p>
	</div>
</div>