<!-- The Grid -->
<div class="w3-row">
	<!-- Left Column -->
	<div class="w3-col m3">
		<!-- Profile -->
		<div class="w3-card-2 w3-round w3-theme-d2">
			<div class="w3-container">
				<h4 class="w3-center"><?php echo "Welcome " . $this->identity(); ?></h4>
				<p class="w3-center" id="profile-pic">
					<script type="text/javascript">
					   var replaced_src;
					   var replace;

					   $.ajax({
							type: "POST",
							url: "/members/profile/get-profile-image",
					   }).done(function(data) {
						    $("#profile-pic").html(data);

						    $('#profile-pic').on('click', 'img', function() {
							    document.getElementById('a-modal').style.display = 'block';

						    	replaced_src = $("#avatar").attr('src');

						    	// load the original image (outside the current/defaults folder)
								replace = replaced_src.replace(/(current|defaults)/g, '');

								$("#avatar-photo").html("<img src='" + replace + "' alt='Avatar' class='w3-center w3-round w3-border' id='enlarged-photo'>");

								cropImage();
						    });
					   }).fail(function(data) {
							alert("Error loading image");
					   });
					</script>
				</p>

				<hr>

				<p id="profile-error"></p>

				<p id="display-name"></p>

				<p id="location"></p>

				<p id="age"></p>

				<script type="text/javascript">
					$.ajax({
						type: "POST",
						url: "/members/profile/get-profile",
						dataType: "json"
					}).done(function(msg) {
						if (msg.display_name === undefined && msg.location === undefined && msg.age === undefined) {
							$('#profile-error').html(msg.message);
							return false;
						} else {
							$("#display-name").html("Display Name: " + msg.display_name !== undefined ? "Display Name: " + msg.display_name : "");
							$("#location").html(msg.location !== undefined ? "Location: " + msg.location : "");
							$("#age").html("Age: " + msg.age !== undefined ? "Age: " + msg.age : "");
						}
					}).fail(function(msg) {
						$("#profile-error").html(msg.message);
					});
				</script>

			</div>
		</div>


		<!-- modal -->
		<div class="w3-modal" id="a-modal">
			<div class="w3-modal-content w3-card-4 w3-theme-d2 w3-round" style="width: 385px;">
				<div class="w3-container">
					<p class="w3-center w3-small">
						<span onclick="document.getElementById('a-modal').style.display = 'none'" class="w3-closebtn">&times;</span>
						Your Profile Picture
					</p>

					<br>

					<p id="avatar-photo" class="w3-center"></p>


					<div class="w3-clear"></div>

					<form method="post" action="<?php echo $this->url('members/profile', array('action' => 'crop-profile-image')); ?>" onsubmit="return checkCoords();">
						<input type="hidden" id="fname" name="fname">
						<input type="hidden" id="x" name="x">
						<input type="hidden" id="y" name="y">
						<input type="hidden" id="w" name="w">
						<input type="hidden" id="h" name="h">
						<input type="submit" value="Crop Profile Picture" class="w3-btn w3-right w3-theme-d2 w3-border w3-border-white w3-round-large">
					</form>



					<br><br>
				</div>
			</div>
		</div>
		<!-- end modal -->

		<br>

		<!-- Accordion -->
		<div class="w3-card-2 w3-round w3-theme-d2">
			<div class="w3-accordion w3-white">
				<button onclick="expand('side-1')"
					class="w3-btn-block w3-theme-d2 w3-left-align">
					<i class="fas fa-users fa-fw w3-margin-right"></i> My
					Groups
				</button>

				<div id="side-1" class="w3-accordion-content w3-container">
					<p id="groups"></p>

					<script type="text/javascript">
						$(document).ready(function() {
							$.ajax({
								type: "GET",
								url: "/members/groups/get-groups",
								dataType: "json",
							}).done(function(msg) {
								if (msg.group_id == undefined || msg.group_name == undefined) {
									$('#groups').html("You aren't a part of any groups.");
									return false;
								} else {
									$.each(msg.group_id, function(i, item) {
										$("#groups").append('<a href="<?php echo $this->url('members/groups', array('action' => 'index')); ?>/group-home/' + msg.group_id[i] + '">' + msg.group_name[i] + '</a><br>');
									})
								};
							}).fail(function(msg) {
								$('#groups').html(msg);
							});
						});
					</script>
				</div>

				<button onclick="expand('side-2')"
					class="w3-btn-block w3-theme-d2 w3-left-align">
					<i class="far fa-calendar-check fa-fw w3-margin-right"></i> My
					Events
				</button>

				<div id="side-2" class="w3-accordion-content w3-container">
					<p id="events"></p>
					
					<script type="text/javascript">
						$(document).ready(function() {
							$.ajax({
								type: "GET",
								url: "/members/events/get-events",
								dataType: "json"
							}).done(function(msg) {
								if (msg == undefined) {
									$('#events').html("You have no events created or a part of.");
									return false;
								} else {
									$.each(msg, function(i, item) {
        								$('#events').append('<a href="<?php echo $this->url('members/events', array('action' => 'index')); ?>/event-home/' + msg[i].event_id + '">' + msg[i].ename + '</a><br>');
									});
								}
							}).fail(function(msg) {
								$('#events').html(msg);
							});
						});
					</script>
				</div>

				<button onclick="expand('side-3')"
					class="w3-btn-block w3-theme-d2 w3-left-align">
					<i class="fas fa-images fa-fw w3-margin-right"></i> My Photos
				</button>

				<div id="side-3" class="w3-accordion-content w3-container">
					<div class="w3-row-padding" id="left-photos">
						<br>
						<?php
						    if (count($this->layout()->my_images) > 0):
						        foreach ($this->layout()->my_images as $image):
						?>
						
						<div class="w3-half">
							<?php echo $image; ?>
						</div>

						<?php
						       endforeach;
						    else:
						?>
						<p>Upload <a href="<?php echo $this->url('members/profile', array('action' => 'upload-file')); ?>">photos</a>!</p> 
						<?php
						       
						    endif;
						?>

						<script type="text/javascript">
							var string_replace;
							var replaced;
							var original_image;

							// event handler on click image
							$('#left-photos img').on('click', function() {
								document.getElementById("p-modal").style.display = "block";

								// get the original image
								// width and height
								original_image = $(this).attr('src');

								$('#original-image').attr('href', original_image);


								// replace the path of the image
								// to display the image title (e.g. my_image)
								// without the extension or directory path
								string_replace = $(this).attr('src');

								replaced = string_replace.replace(/(images|profile|<?php echo $this->identity(); ?>|.jpg|.jpeg|.png|)/gi, '')
								.replace(/\//g, '');

								$('#picked_image').html(replaced.charAt(0).toUpperCase() + replaced.slice(1));

								$('#clicked-photo').html("<img class=\"w3-round w3-border\" style=\"width: 250px; height: 170px;\" id=\"other-photo\" src=" + $(this).attr('src') + ">");
							});


						</script>

						<!-- image modal -->
						<div class="w3-modal" id="p-modal">
							<div class="w3-modal-content w3-card-4 w3-theme-d2 w3-round" style="width: 400px;">
								<div class="w3-container">
									<p class="w3-center w3-small" id="photo-modal">
										<span onclick="document.getElementById('p-modal').style.display = 'none'" class="w3-closebtn">&times;</span>
									</p>

									<p id="picked_image" class="w3-center w3-small"></p>

									<br>

									<div class="w3-row-padding w3-center" id="clicked-photo"></div>

									<br><br>

									<div class="w3-display-container">
										<div class="w3-display-left">
											<p class="w3-small">
												<a target="_blank" id="original-image" class="w3-theme-d2">View Original Image</a>
											</p>
											<br>
										</div>

										<div class="w3-display-right">
											<p class="w3-small">
												<button id="make-profile-photo" class="w3-btn w3-theme-d2 w3-round-large">Make Profile Picture</button>
											</p>
											<br>
										</div>
									</div>

									<br>

									<script type="text/javascript">
										$('#make-profile-photo').on('click', function() {
											$.ajax({
												type: "POST",
												url: "/members/profile/change-profile-picture",
												data: { image: $('#other-photo').attr('src') }
											}).done(function() {
												document.getElementById('p-modal').style.display = 'none';

												$('#profile-pic').load('/members/profile/get-profile-image');
											});
										});
									</script>
									<div class="w3-clear"></div>
								</div>
							</div>
						</div>
						<!-- end modal -->

					</div>
				</div>
				
				<button onclick="expand('side-4');" class="w3-btn-block w3-theme-d2 w3-left-align">
					<i class="far fa-id-card fa-fw w3-margin-right"></i> My Friends
				</button>
				
				<div id="side-4" class="w3-accordion-content w3-container">
					<p id="friends"></p>
				</div>
				
				<script type="text/javascript">
					$.getJSON('/members/friends/get-friends', function() {
					}).done(function(data) {
						var friends = data.friend_list.join("<br />");
						$('#friends').html(friends);
					}).fail(function(msg) {
						$('#friends').html(msg.message);
					});
				</script>
				
				<button onclick="expand('side-5');" class="w3-btn-block w3-theme-d2 w3-left-align">
					<i class="fas fa-video fa-fw w3-margin-right"></i> My Videos
				</button>
				
				<div id="side-5" class="w3-accordion-content w3-container">
					<div class="w3-row-padding" id="left-videos">
					<br>
						<?php
						    if (count($this->layout()->my_videos) > 0):
						        foreach ($this->layout()->my_videos as $vids):
						?>
						
						<div class="w3-half">
							<?php echo $vids; ?>
						</div>

						<?php
						       endforeach;
						    else:
						?>
						<p>Upload <a href="<?php echo $this->url('members/profile', array('action' => 'upload-file')); ?>">videos</a>!</p> 
						<?php
						       
						    endif;
						?>
					</div>
				</div>
				
				<script type="text/javascript">
					// event handler on click video
					$('#left-videos video').on('click', function() {
						document.getElementById("v-modal").style.display = "block";

						$('#clicked-video').html("<video class=\"w3-round w3-border\" style=\"width: 100%; height: 100%;\" id=\"other-video\" controls><source src=" + $(this).find('source').attr('src') + " type=\"video/mp4\"></video>");
					});
				</script>
				
				<!-- video modal -->
				<div class="w3-modal" id="v-modal">
					<div class="w3-modal-content w3-card-4 w3-theme-d2 w3-round" style="width: 600px; height: 400px;">
						<div class="w3-container">
							<p class="w3-center w3-small" id="video-modal">
								<span onclick="document.getElementById('v-modal').style.display = 'none'" class="w3-closebtn" id="close-video">&times;</span>
								
								<script type="text/javascript">
									$('#close-video').on('click', function() {
										$('video').trigger('pause');
									});
								</script>
							</p>
							
							<br><br>
							
							<div class="w3-row-padding w3-center" id="clicked-video"></div>

							<br><br>

							<div class="w3-clear"></div>
						</div>
					</div>
				</div>
			    <!-- end video modal -->
			    
			    <script type="text/javascript">
					var modal = document.getElementById('p-modal');
					var modal2 = document.getElementById('v-modal');                                                                                                                                                                                                                                                                                                                                                             

					window.onclick = function(event) {
						if (event.target == modal2) {
							$('video').trigger('pause');
							modal2.style.display = 'none';
						}
											
						if (event.target == modal) {
							modal.style.display = 'none';
						}
					}
				</script>
				
				
				
				<!-- send message modal -->
				<div class="w3-modal" id="send-msg-modal">
					<div class="w3-modal-content w3-card-4 w3-theme-d2 w3-round" style="width: 800px; height: 500px;">
						<div class="w3-container">
							<p class="w3-center w3-small" id="send-message-modal">
								Send Message
								<span onclick="document.getElementById('send-msg-modal').style.display = 'none'" class="w3-closebtn" id="close-send-msg">&times;</span>
							</p>
							
							<br><br>
							
							<div class="w3-row-padding" id="send-message-fields">
								<label><b>To</b></label>
								<select class="w3-select" name="members" id="members">
									<option value="" disabled selected>Choose a user</option>
									<?php foreach ($this->members as $value): ?>
										<option value="<?php echo $value['username']; ?>"><?php echo $value['username']; ?></option>
									<?php endforeach; ?>
								</select>
								<br><br>
								<label><b>Subject</b></label>
								<input type="text" class="w3-input w3-border" id="subject">
								<br>
								<label><b>Message</b></label>
								<textarea class="w3-input w3-border" style="resize: none;" id="message"></textarea>
								<br>
							</div>
							
							<div class="w3-row-padding w3-right">
								<button class="w3-btn w3-white w3-round" id="send-msg-button">Send Message</button>
							</div>
							
							<br><br>
							
							<p class="w3-center" id="send-message-result"></p>
							
							<div class="w3-clear"></div>
							
							<script type="text/javascript">
								$('#send-msg-button').on('click', function() {
									$.post('/members/send-message', { to: $('#members option:selected').val(), subject: $('#subject').val(), message: $('#message').val() }, function(data) {
										if (data.success != undefined) {
											$('#send-message-result').html(data.success);
										} else {
											$('#send-message-result').html(data.error);
										} 
									}, "json");
								});
							</script>
						</div>
					</div>
				</div>
				<!-- end send message modal -->
				<script type="text/javascript">
					var modal = document.getElementById('send-msg-modal');                                                                                                                                                                                                                                                                                                                                                             

					window.onclick = function(event) {				
						if (event.target == modal) {
							modal.style.display = 'none';
						}
					}
				</script>
			</div>
		</div>
		<br class="w3-clear">
		<!-- End Left Column -->
	</div>


	<!-- Middle Column -->
	<div class="w3-col m7">
		<div class="w3-row-padding">
			<div class="w3-col m12">
				<div class="w3-card-2 w3-round w3-white">
					<div class="w3-container w3-padding">
						<h6 class="w3-opacity"><a href="<?php echo $this->url('members/send-message', array('action' => 'index')); ?>" id="smg">
						Send Message</a></h6>
						
						<script type="text/javascript">
							// event handler for on click send messages link
							$('#smg').on('click', function(e) {
								e.preventDefault();

								document.getElementById("send-msg-modal").style.display = "block";
							});
						</script>
					</div>
				</div>
			</div>
		</div>
		<br><br>
		<div class="w3-row-padding">
			<div class="w3-col m12">
				<div class="w3-card-2 w3-round w3-white">
					<div class="w3-container w3-padding">
					<table class="w3-table-all" id="msg-table">
						<thead>
							<tr>
								<th>From</th>
								<th>Subject</th>
								<th>Message</th>
								<th>Date Sent</th>
								<th></th>
							</tr>
						</thead>
						
						
						<?php 
							  foreach ($this->paginator as $value):
                                  if ($value->active == 1):
						?>
								  <tr class="w3-hover-text-red w3-text-black">
								  	  <td>
								  	      <b><?php echo $value->from; ?></b>
								  	  </td>
								  	  
								  	  <td>
								  	      <b><?php echo $value->subject; ?></b>
								  	  </td>
								  	  
								  	  <td>
								  	      <b><?php echo $value->message; ?></b>
								  	  </td>
								  	  
								  	  <td>
								  	      <b><?php echo $value->date_sent; ?></b>
								  	  </td>
								  	  
								  	  <td>
										 <input type="checkbox" class="w3-check">&nbsp; Mark As Read
									  </td>
								  </tr>
						<?php else: ?>
							<tr class="w3-hover-text-red w3-text-black">
								<td>
									<?php echo $value->from; ?>	
								</td>
								
								<td>
									<?php echo $value->subject; ?>
								</td>
								
								<td>
									<?php echo $value->message; ?>
								</td>

								<td>
									<?php echo $value->date_sent; ?>
								</td>	
								
								<td>
									<input type="checkbox" class="w3-check">&nbsp; Mark As Unread
								</td>							
							</tr>
						<?php 
						      endif;
						      endforeach;
						?>
					</table>
					
					<?php echo $this->paginationControl($this->paginator, 'sliding', 'paginator.phtml', array('route' => 'members/messages')); ?>
					<br class="w3-clear">
					</div>
				</div>
			</div>
		</div>
		<!-- End Middle Column -->
	</div>
	
	<!-- right column -->
	<div class="w3-col m2">
		<div class="w3-card-2 w3-round w3-white" style="max-height: 700px; overflow-y: scroll; overflow-x: hidden;" id="friend-list">
			<div class="w3-container">
				<p class="w3-center">Friends Online</p>
				<hr style="border: 1px solid; box-shadow: 0 0 5px 1px black inset;">
				
				<p class="w3-left" id="friends-online"></p>
			</div>
		</div>
	<!-- end right column -->
	</div>

	<!-- End Grid -->
</div>