<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<title>Members</title>

		<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css" type="text/css">
    	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    	<link rel="stylesheet" href="http://www.w3schools.com/lib/w3-theme-blue-grey.css">
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


		<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/upload-file.css" type="text/css">
		<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/styles.css" type="text/css">
		<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/jquery.Jcrop.min.css" type="text/css">


    	<script src="https://code.jquery.com/jquery-3.1.1.min.js" type="text/javascript"></script>
    	<script src="<?php echo $this->basePath(); ?>/js/jquery.Jcrop.min.js"></script>

    	<script src="<?php echo $this->basepath(); ?>/js/jquery.uploadfile.min.js"></script>

		<script src="<?php echo $this->basePath(); ?>/js/resize.js" type="text/javascript"></script>

    	<script src="<?php echo $this->basePath(); ?>/js/createProfile.js" type="text/javascript"></script>
    	<script src="<?php echo $this->basePath(); ?>/js/profile.js" type="text/javascript"></script>
    	<script src="<?php echo $this->basePath(); ?>/js/quickProfileEdit.js" type="text/javascript"></script>
    	<script src="<?php echo $this->basePath(); ?>/js/editPhoto.js" type="text/javascript"></script>

		<style>
            html, body, h1, h2, h3, h4, h5 {
                font-family: "Open Sans", sans-serif;
            }
            
            .w3-accordion-content a {
            	padding: 0px 0px;
            	display: inline;
            }
            
            .w3-accordion-content a:hover {
            	background-color: #fff;
            }
        </style>

		<script type="text/javascript">
			function cropImage() {
				$('#fname').val(replace);


				$('#enlarged-photo').Jcrop({
					trackDocument: true,
					aspectRatio: 1,
					onSelect: update,
					boxWidth: 350,
					boxHeight: 400
				});
			}

			$(function() {
				var settings = {
					url: "/members/profile/upload-file",
					method: "POST",
					allowedTypes: "jpg,png",
					fileName: "<?php echo $this->identity(); ?>",
					multiple: true,

					onSuccess: function (files, data, xhr) {
						$('#status').html("<p class=\"w3-center w3-text-green\">Upload successful!</p>");
					},

					onError: function (files, status, errMsg) {
						$('#status').html("<p class=\"w3-center w3-text-red\">Upload failed.</p>");
					}
				}

				$('#multiplefileuploader').uploadFile(settings);
			});
		</script>
    </head>

	<body class="w3-theme-l5">

        <!-- Navbar -->
		<div class="w3-top">
 			<ul class="w3-navbar w3-theme-d2 w3-left-align w3-large">
  				<li class="w3-bar-item w3-hide-medium w3-hide-large w3-opennav w3-right">
    				<a class="w3-padding-large w3-hover-pale-green w3-large w3-theme-d2" href="javascript:void(0);" id="open-nav"><i class="fa fa-bars"></i></a>
  				</li>

  				<li><a href="<?php echo $this->url('members', array('action' => 'index')); ?>" class="w3-padding-16 w3-padding-large w3-theme-d4"><i class="fa fa-home w3-margin-right"></i>Home</a></li>

  				<li class="w3-hide-small"><a href="<?php echo $this->url('home/forum', array('action' => 'index')); ?>" class="w3-padding-16 w3-padding-large w3-hover-pale-green" title="Forums"><i class="fa fa-globe"></i></a></li>

  				<li class="w3-hide-small"><a href="<?php echo $this->url('members/account', array('action' => 'index')); ?>" class="w3-padding-16 w3-padding-large w3-hover-pale-green" title="Account Settings"><i class="fa fa-user"></i></a></li>

  				<li class="w3-hide-small"><a href="<?php echo $this->url('members/messages', array('action' => 'index')); ?>" class="w3-padding-16 w3-padding-large w3-hover-pale-green" title="Messages"><i class="fa fa-envelope"></i></a></li>

				<li class="w3-hide-small"><a href="<?php echo $this->url('members/profile', array('action' => 'index')); ?>" class="w3-padding-16 w3-padding-large w3-hover-pale-green" title="Profile"><i class="fa fa-address-book"></i></a></li>

				<li class="w3-hide-small"><a href="<?php echo $this->url('members/groups', array('action' => 'index')); ?>" class="w3-padding-16 w3-padding-large w3-hover-pale-green" title="Groups"><i class="fa fa-users"></i></a></li>

				<li class="w3-hide-small"><a href="<?php echo $this->url('members/events', array('action' => 'index')); ?>" class="w3-padding-16 w3-padding-large w3-hover-pale-green" title="Events"><i class="fa fa-calendar-check-o"></i></a></li>

 				<li class="w3-hide-small"><a href="<?php echo $this->url('members/friends', array('action' => 'index')); ?>" class="w3-padding-16 w3-padding-large w3-hover-pale-green" title="Friends"><i class="fa fa-id-card-o"></i></a></li>
 				
 				<li class="w3-hide-small"><a href="<?php echo $this->url('home/logout', array('action' => 'member-logout')); ?>" class="w3-padding-16 w3-padding-large w3-hover-pale-green" title="Logout"><i class="fa fa-power-off"></i></a></li>
 			</ul>
		</div>

        <!-- Navbar on small screens -->
		<div id="small-nav" class="w3-bar-block w3-theme-d2 w3-hide w3-hide-large w3-hide-medium w3-large">
    		<a class="w3-bar-item w3-button w3-padding-large" href="<?php echo $this->url('home/forum', array('action' => 'index')); ?>">Forums</a>
    		<a class="w3-bar-item w3-button w3-padding-large" href="<?php echo $this->url('members/account', array('action' => 'index')); ?>">My Account</a>
    		<a class="w3-bar-item w3-button w3-padding-large" href="<?php echo $this->url('members/messages', array('action' => 'index')); ?>">Messages</a>
  			<a class="w3-bar-item w3-button w3-padding-large" href="<?php echo $this->url('members/profile', array('action' => 'index')); ?>">Profile</a>
  			<a class="w3-bar-item w3-button w3-padding-large" href="<?php echo $this->url('members/groups', array('action' => 'index')); ?>">Groups</a>
  			<a class="w3-bar-item w3-button w3-padding-large" href="<?php echo $this->url('members/events', array('action' => 'index')); ?>">Events</a>
  			<a class="w3-bar-item w3-button w3-padding-large" href="<?php echo $this->url('members/friends', array('action' => 'index')); ?>">Friends</a>
  			<a class="w3-bar-item w3-button w3-padding-large" href="<?php echo $this->url('home/logout', array('action' => 'member-logout')); ?>">Logout</a>
		</div>


        <!-- Page Container -->
		<div class="w3-container w3-content" style="max-width: 1400px; margin-top: 80px;">
 			<?php echo $this->content; ?>
        <!-- End Page Container -->
		</div>

	<br><br><br>

    <!-- Footer -->
	<footer class="w3-container w3-bottom w3-theme-d2 w3-padding-tiny w3-margin-0">
		<p class="w3-center">&copy; <?php echo date('Y'); ?> Jimmy Sole. All Rights Reserved.</p>
	</footer>


	<script>
		// Accordion
		function expand(id) {
    		var x = $('#' + id);

    		if (!x.hasClass("w3-show")) {
        		x.addClass("w3-show");
        		x.closest('w3-show').prev().addClass('w3-theme-d2');
    		} else {
        		x.removeClass('w3-show');
        		x.closest('w3-show').prev().removeClass('w3-theme-d2');
    		}
	 	}

		$('#open-nav').on('click', function() {
			if (!$('#small-nav').hasClass('w3-show')) {
				$('#small-nav').addClass('w3-show');
			} else {
				$('#small-nav').removeClass('w3-show');
			}
		});
	</script>

</body>
</html>
