<div class="w3-row-padding">
	<!-- group members currently online col (left) -->
	<div class="w3-col m3">
		<div class="w3-card-2 w3-round w3-theme-d2">
			<div class="w3-container w3-round w3-theme-d2">
				<h6 class="w3-center" style="border-bottom: 1px solid #ddd;">Group Members Online</h6>
				
				<p id="members-online"></p>
				
				<script type="text/javascript">
				$(function() {
					function buildOnlineMemberList() {
					    $.ajax({
					    	type: "GET",
					      	url: "/members/groups/get-group-members-online",
					      	dataType: "json",
					    }).done(function(msg) {
					    	if (msg.display_name == "" || msg.display_name == undefined) {
								$('#members-online').html("No group members are online.");
								return;
							} else {
						    	var displayNames = msg.display_name.join('<br />');
						    	$("#members-online").html(displayNames);
							}
					    }).fail(function() {
					    	$('#members-online').html("Error retrieving group list.");
					    });
					}

					setInterval(function() {
					   buildOnlineMemberList();
					}, 5000);

					buildOnlineMemberList();
				});
				</script>
			</div>
		</div>
		
		<br><br>
		
		<div class="w3-card-2 w3-round-w3-theme-d2">
			<div class="w3-container w3-round w3-theme-d2">
				<h6 class="w3-center" style="border-bottom: 1px solid #ddd;">Event Functions</h6>
				
				<p id="event-opts">
					<a href="<?php echo $this->url('members/events', array('action' => 'create-event')); ?>">Create Event</a>
					
					<br>
					
					<a href="<?php echo $this->url('members/events', array('action' => 'view-events')); ?>">View Events</a>
					
					<br>
					
					<a href="<?php echo $this->url('members/events', array('action' => 'index')); ?>">Your Events</a>
					
					<br>
					
					<a href="<?php echo $this->url('members/events', array('action' => 'delete-event')); ?>">Delete Event</a>
				</p>
				
				<script type="text/javascript">
					$('#event-opts a').addClass('w3-hover-text-red');
				</script>
			</div>
		</div>
	</div>
	<!-- end left column -->

	<!-- middle column -->
	<div class="w3-col m7">
		<div class="w3-row-padding">
			<div class="w3-col m12">
				<div class="w3-card-2 w3-round w3-white">
					<div class="w3-container w3-padding">
						<h2
							class="w3-center w3-white w3-border w3-border-white w3-round-xlarge"
							style="text-shadow: 1px 1px 0 #000">
							<?php echo $this->event_info['info']['event_name']; ?>
						</h2>
					</div>
				</div>
			</div>
		</div>


		<div class="w3-col m-12">
			<div class="w3-container w3-card-2 w3-theme-d2 w3-margin w3-round">
				<div class="w3-container w3-padding">
					<br class="w3-clear">

					<div class="w3-responsive">
						<table class="w3-table-all w3-card-4">
							<thead>
								<tr class="w3-white">
									<th style="white-space: nowrap;">Event Name</th>
									<th style="white-space: nowrap;">Event Description</th>
									<th style="white-space: nowrap;">Start Date</th>
									<th style="white-space: nowrap;">End Date</th>
								</tr>
							</thead>

							<tr class="w3-text-black">
								<td style="width: 15%;"><?php echo $this->event_info['info']['event_name']; ?></td>
								<td style="width: 45%;"><?php echo $this->event_info['info']['event_description']; ?></td>
								<td style="width: 15%;"><?php echo date('Y-m-d', strtotime($this->event_info['info']['start_date'])); ?></td>
								<td style="width: 15%;"><?php echo date('Y-m-d', strtotime($this->event_info['info']['end_date'])); ?></td>
							</tr>
						</table>
					</div>
					
					<br class="w3-clear">
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end content -->