<div class="w3-row-padding">
	<!-- group members currently online col (left) -->
	<div class="w3-col m3">
		<div class="w3-card-2 w3-round w3-theme-d2">
			<div class="w3-container w3-round w3-theme-d2">
				<h6 class="w3-center" style="border-bottom: 1px solid #ddd;">Group Members Online</h6>
				
				<p id="members-online"></p>
				
				<script type="text/javascript">
				$(function() {
					function buildOnlineMemberList() {
					    $.ajax({
					    	type: "GET",
					      	url: "/members/groups/get-one-group-members-online/" + location.pathname.split("/")[4],
					      	dataType: "json",
					    }).done(function(msg) {
					    	if (msg.display_name == "" || msg.display_name == undefined) {
								$('#members-online').html("No group members are online.");
								return;
							} else {
						    	var displayNames = msg.display_name.join('<br />');
						    	$("#members-online").html(displayNames);
							}
					    }).fail(function() {
					    	$('#members-online').html("Error retrieving group list.");
					    });
					}

					setInterval(function() {
					   buildOnlineMemberList();
					}, 5000);

					buildOnlineMemberList();
				});
				</script>
			</div>
		</div>
		
		<br><br>
		
		<div class="w3-card-2 w3-round w3-theme-d2">
			<div class="w3-container w3-round w3-theme-d2">
				<h6 class="w3-center" style="border-bottom: 1px solid #ddd;">Group Functions</h6>
					<p id="group-opts">
						<a href="<?php echo $this->url('members/groups', array('action' => 'create-group')); ?>">Create Group</a>

						<br>

						<a href="<?php echo $this->url('members/lists-groups', array('action' => 'index')); ?>">Browse Groups</a>

						<br>

						<a href="<?php echo $this->url('members/groups', array('action' => 'post-group-event')); ?>">Post Group Event</a>

						<br>

						<a href="<?php echo $this->url('members/groups', array('action' => 'post-group-message')); ?>">Post Group Message</a>

						<br>

						<a href="<?php echo $this->url('members/groups', array('action' => 'start-group-chat')); ?>">Start Group Chat</a>
					</p>

					<script type="text/javascript">
						$('#group-opts a').addClass('w3-hover-text-red');
					</script>
			</div>
		</div>
		<br class="w3-clear">
	</div>
	
	<!-- end left column -->

	
	<!-- middle column -->
	<div class="w3-col l9 m8">
		<div class="w3-row-padding">
			<div class="w3-col l12 m8">
				<div class="w3-card-2 w3-round w3-white">
					<div class="w3-container w3-padding">
						<h2
							class="w3-center w3-white w3-border w3-border-white w3-round-xlarge"
							style="text-shadow: 1px 1px 0 #000">
							<?php echo $this->group_info['info']['group_name']; ?>
						</h2>
					</div>
				</div>
			</div>
		</div>


		<div class="w3-col l12 m8">
			<div class="w3-container w3-card-2 w3-theme-d2 w3-margin w3-round">
				<div class="w3-container w3-padding">
					<br class="w3-clear">

					<div class="w3-responsive">
						<table class="w3-table-all w3-card-4">
							<thead>
								<tr class="w3-white">
									<th style="white-space: nowrap;">Group Name</th>
									<th style="white-space: nowrap;">Group Creator</th>
									<th style="white-space: nowrap;">Group Description</th>
									<th style="white-space: nowrap;">Group Admins</th>
									<th style="white-space: nowrap;">Group Members</th>
									<th style="white-space: nowrap;"></th>
								</tr>
							</thead>

							<tr class="w3-text-black">
								<td style="text-overflow: ellipsis;"><?php echo $this->group_info['info']['group_name']; ?></td>
								<td style="text-overflow: ellipsis;"><?php echo $this->group_info['info']['group_creator']; ?></td>
								<td style="text-overflow: ellipsis;"><?php echo $this->group_info['info']['group_description']; ?></td>
								<td style="text-overflow: ellipsis;"><?php echo $this->group_info['admins']; ?></td>
								<td style="text-overflow: ellipsis;"><?php echo $this->group_info['members']; ?></td>
								<?php if ($this->group_info['members'] == 'No members exist in this group.'): ?>
								<td></td>
								<?php else: ?>
								<td><a id="leave-group" href="<?php echo $this->url('members/groups', array('action' => 'leave-group', 'id' => $this->group_info['info']['id'])); ?>">
									Leave Group</a></td>
								<?php endif; ?>
							</tr>
						</table>

						<script type="text/javascript">
							$('#leave-group').on('click', function(e) {
								// prevent the page from going to the link
								e.preventDefault();

								if (confirm("Are you sure you want to leave this group?")) {
									// send request to leave the group
									// and return the response via json
									$.ajax({
										type: "POST",
										url: "/members/groups/leave-group/" + location.pathname.split("/")[4],
										dataType: "json",
									}).done(function(msg) {
										// return back to the groups page
										$('#g-leave-modal').css('display', 'block');
										$('#group-leave p').html("You have left the group");
									}).fail(function(msg) {
										$('#error-modal').css('display', 'block');
										$('#group-error p').html(msg.group_error);
									});
								} else {
									return false;
								}
							});
						</script>

						<br class="w3-clear">
						
						<div class="w3-modal" id="error-modal">
							<div class="w3-modal-content w3-card-4 w3-theme-d2 w3-round" style="width: 320px;">
								<div class="w3-container">
									<p class="w3-center w3-small" id="error-modal-x">
										<span onclick="document.getElementById('error-modal').style.display = 'none'" class="w3-closebtn">&times;</span>
									</p>
									
									<div class="w3-row-padding w3-center" id="group-error">
										<p></p>
									</div>
								</div>
							</div>
						</div>
						
						<div class="w3-modal" id="g-leave-modal">
							<div class="w3-modal-content w3-card-4 w3-theme-d2 w3-round" style="width: 260px; height: 200px;">
								<div class="w3-container">
									<p class="w3-center w3-small" id="group-modal-x">
										<span onclick="document.getElementById('g-leave-modal').style.display = 'none'" class="w3-closebtn" id="x">&times;</span>
									</p>
									
									<script type="text/javascript">
										$('#x').on('click', function() {
											location.href = "/members/groups";
										});
									</script>
									
									<div class="w3-row-padding w3-center" id="group-leave">
										<p></p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end content -->
