<div class="w3-row">
	<div class="w3-col sm-12 w3-center">
		<p class="w3-large">
			<?php echo $this->flashMessenger()
			    ->setMessageOpenFormat('<div%s<p>')
			    ->setMessageSeparatorString('</p><p>')
			    ->setMessageCloseString('</p></div>')
			    ->render('success'); ?>
		</p>
		<br>
		<p class="w3-large">
			<a href="<?php echo $this->url('members/groups', array('action' => 'index')); ?>">Back To Groups Page</a>
		</p>
	</div>
</div>