<div class="w3-row">
	<div class="w3-col sm-12 w3-center">
		<p class="w3-large">
			<?php echo $this->flashMessenger()
			           ->setMessageOpenFormat('<div%s<p>')
			           ->setMessageSeparatorString('</p><p>')
			           ->setMessageCloseString('</p></div>')
			           ->render('error'); ?>
			<br>
			<a href="<?php echo $this->url('members/groups', array('action' => 'create-group')); ?>">Back To Create Group Page</a>
		</p>
	</div>
</div>