<div class="w3-row-padding">
	<div class="w3-col-m7">
		<div class="w3-row-padding">
			<div class="w3-col m12">
				<div class="w3-card-4 w3-round w3-white">
					<div class="w3-container w3-padding">
						<h2 class="w3-center">Create A Group</h2>
						<br>
						<?php 
						    $this->form->setAttribute('action', $this->url('members/groups', array('action' => 'cgroup')));
						    
						    $this->form->prepare();
						    
						    echo $this->form()->openTag($this->form);
						?>
						
						<br>
						
						<?php 
						
						    echo $this->formRow($this->form->get('group-name'));
						    
						    echo "<div id=\"group-name-error\" class=\"w3-panel w3-red w3-card-2\" style=\"display: none;\">
			                         <span onclick=\"this.parentElement.style.display='none'\" class=\"w3-button w3-red w3-large w3-right w3-hover-red\">
			                             &times;
			                         </span>
			                      ";
						    
						    echo "<p>Group Name cannot be empty.</p>";
						    
						    echo "</div>";
						    
						    echo "<div id=\"group-size-error\" class=\"w3-panel w3-red w3-card-2\" style=\"display: none;\">
						             <span onclick=\"this.parentElement.style.display='none'\" class=\"w3-button w3-red w3-large w3-right w3-hover-red\">
						                 &times;
						             </span>
						          ";
						    
						    echo "<p>Group Name size must be between 10 and 100 characters.</p>";
						    
						    echo "</div>";
						    
						    
						    echo "<p>";
						    
						    echo $this->formCheckbox($this->form->get('join_authorization'));
						    
						    echo "&nbsp;<label>Enable Join Authorization</label>";
						    
						    echo "</p>";
						    
						    
						    echo "<p>";
						    
						    echo $this->formCheckbox($this->form->get('closed_to_public'));
						    
						    echo "&nbsp;<label>Enable Private Group</label>";
						    
						    echo "</p>";
						    
						    
						    echo $this->formElement($this->form->get('csrf_security'));
						    
						    
						    echo "<br><br>";
						    
						    echo $this->formElement($this->form->get('submit'));
						    
						    echo $this->form()->closeTag();
						
						?>
					</div>
					
					<script type="text/javascript">
						$('#group-name').on('blur', function() {
							if ($(this).val() == "" || $(this).val() == undefined) {
								$('#group-name-error').css('display', 'block');
								$(this).focus();
								return;
							}

							if ($(this).val().length < 10 || $(this).val().length > 100) {
								$('#group-size-error').css('display', 'block');
								$(this).focus();
								return;
							}
						});
					</script>
				</div>
			</div>
		</div>
	</div>
</div>