<div class="w3-row-padding">
	<!-- group members currently online col (left) -->
	<div class="w3-col m3">
		<div class="w3-card-2 w3-round w3-theme-d2">
			<div class="w3-container w3-round w3-theme-d2">
				<h6 class="w3-center" style="border-bottom: 1px solid #ddd;">Group Members Online</h6>
				
				<p id="members-online"></p>
				
				<script type="text/javascript">
				$(function() {
					function buildOnlineMemberList() {
					    $.ajax({
					    	type: "GET",
					      	url: "/members/groups/get-one-group-members-online/" + location.pathname.split("/")[4],
					      	dataType: "json",
					    }).done(function(msg) {
					    	if (msg.display_name == "" || msg.display_name == undefined) {
								$('#members-online').html("No group members are online.");
								return;
							} else {
						    	var displayNames = msg.display_name.join('<br />');
						    	$("#members-online").html(displayNames);
							}
					    }).fail(function() {
					    	$('#members-online').html("Error retrieving group list.");
					    });
					}

					setInterval(function() {
					   buildOnlineMemberList();
					}, 5000);

					buildOnlineMemberList();
				});
				</script>
			</div>
		</div>
	</div>
	<!-- end left column -->

	<!-- middle column -->
	<div class="w3-col m7">
		<div class="w3-row-padding">
			<div class="w3-col m12">
				<div class="w3-card-2 w3-round w3-white">
					<div class="w3-container w3-padding">
						<h2
							class="w3-center w3-white w3-border w3-border-white w3-round-xlarge"
							style="text-shadow: 1px 1px 0 #000">
							<?php echo $this->group_info['info']['group_name']; ?>
						</h2>
					</div>
				</div>
			</div>
		</div>


		<div class="w3-col m-12">
			<div class="w3-container w3-card-2 w3-theme-d2 w3-margin w3-round">
				<div class="w3-container w3-padding">
					<br class="w3-clear">

					<div class="w3-responsive">
						<table class="w3-table-all w3-card-4">
							<thead>
								<tr class="w3-white">
									<th style="white-space: nowrap;">Group Name</th>
									<th style="white-space: nowrap;">Group Creator</th>
									<th style="white-space: nowrap;">Group Admins</th>
									<th style="white-space: nowrap;">Group Members</th>
									<th style="white-space: nowrap;"></th>
								</tr>
							</thead>

							<tr class="w3-text-black">
								<td><?php echo $this->group_info['info']['group_name']; ?></td>
								<td><?php echo $this->group_info['info']['group_creator']; ?></td>
								<td><?php echo $this->group_info['admins']; ?></td>
								<td><?php echo $this->group_info['members']; ?></td>
								<?php if ($this->group_info['members'] == 'No members found.'): ?>
								<td></td>
								<?php else:?>
								<td><a id="leave-group" href="<?php echo $this->url('members/groups', array('action' => 'leave-group', 'id' => $this->group_info['info']['id'])); ?>">
									Leave Group</a></td>
								<?php endif;?>
							</tr>
						</table>

						<script type="text/javascript">
							$('#leave-group').on('click', function(e) {
								// prevent the page from going to the link
								e.preventDefault();

								if (confirm("Are you sure you want to leave this group?")) {
									// send request to leave the group
									// and return the response via json
									$.ajax({
										type: "POST",
										url: "/members/groups/leave-group/" + location.pathname.split("/")[4],
										dataType: "json",
									}).done(function(msg) {
										// return back to the groups page
										location.href = "/members/groups";
									}).fail(function(msg) {
										alert(msg.group_error);
									});
								} else {
									return false;
								}
							});
						</script>

						<br class="w3-clear">
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end content -->
