<div class="w3-row-padding">
	<!-- group members currently online col (left) -->
	<div class="w3-col m3" id="left-online">
		<div class="w3-card-2 w3-round w3-theme-d2">
			<div class="w3-container w3-round w3-theme-d2">
				<h6 class="w3-center" style="border-bottom: 1px solid #ddd;">Group Members Online</h6>

				<p id="members-online"></p>

				<script type="text/javascript">
					$(function() {
						 function buildOnlineMemberList() {
							$.ajax({
								type: "GET",
							    url: "/members/groups/get-group-members-online",
							    dataType: "json"
							}).done(function(msg) {
								if (msg.display_name == "" || msg.display_name == undefined) {
									$('#members-online').html("No group members are online.");
									return false;
								} else {
							    	var displayNames = msg.display_name.join('<br />');
							    	$("#members-online").html(displayNames);
								}
							}).fail(function() {
							   $('#members-online').html("Error retrieving group list.");
							});
						 }

						 setInterval(function() {
						  	buildOnlineMemberList();
						 }, 5000);

					     buildOnlineMemberList();
					});
				</script>
			</div>
		</div>

		<br><br>


		<div class="w3-card-2 w3-round w3-theme-d2">
			<div class="w3-container w3-round w3-theme-d2">
				<h6 class="w3-center" style="border-bottom: 1px solid #ddd;">Group Functions</h6>
					<p id="group-opts">
						<a href="<?php echo $this->url('members/groups', array('action' => 'create-group')); ?>">Create Group</a>

						<br>

						<a href="<?php echo $this->url('members/groups', array('action' => 'view-groups')); ?>">Browse Groups</a>

						<br>

						<a href="<?php echo $this->url('members/groups', array('action' => 'post-group-event')); ?>">Post Group Event</a>

						<br>

						<a href="<?php echo $this->url('members/groups', array('action' => 'post-group-message')); ?>">Post Group Message</a>

						<br>

						<a href="<?php echo $this->url('members/groups', array('action' => 'start-group-chat')); ?>">Start Group Chat</a>
					</p>

					<script type="text/javascript">
						$('#group-opts a').addClass('w3-hover-text-red');
					</script>
			</div>
		</div>
	</div>
	<!-- end left column -->


   <?php
		  if (!is_array($this->groups)):
   ?>
	<div class="w3-responsive">
		<p class="w3-center" id="no-groups">You aren't part of any groups!<br><br>
			<a href="<?php echo $this->url('members/groups', array('action' => 'view-more')); ?>">Search Groups</a>
		</p>
	</div>

	<script type="text/javascript">
		$('#left-online').addClass('w3-hide');
		$('#middle-col').addClass('w3-display-middle');
    </script>
    <?php else: ?>

	<!-- middle column -->
	<div class="w3-col m7" id="middle-col">
		<div class="w3-row-padding">
			<div class="w3-col m12">
				<div class="w3-card-2 w3-round w3-white">
					<div class="w3-container w3-padding">
						<h2
							class="w3-center w3-white w3-border w3-border-white w3-round-xlarge"
							style="text-shadow: 1px 1px 0 #000">Your groups (First 5)</h2>

						<p class="w3-left">To view more information about your group(s),
							just click the group id number to the left of the table below.</p>
					</div>
				</div>
			</div>
		</div>

		<div class="w3-container w3-card-2 w3-theme-d2 w3-margin w3-round">
			<br class="w3-clear">
			<div class="w3-responsive">
				<table class="w3-table-all w3-card-4" style="width: 100%;">
					<thead>
						<tr class="w3-white">
							<th>Group Id</th>
							<th>Group Name</th>
						</tr>
					</thead>

		<?php
		        foreach ($this->groups as $value):
        ?>
					<tr class="w3-hover-text-red w3-text-black">
						<td><a
							href="<?php echo $this->url('members/groups', array('action' => 'group-home', 'id' => $value['group_id'])); ?>">
							<?php echo $value['group_id']; ?></a></td>
						<td><?php echo $value['g_name']; ?></td>
					</tr>
<?php
                endforeach;

               
?>
				</table>
			</div>
			
			<div class="w3-right w3-padding">
				<a href="<?php echo $this->url('members/groups', array('action' => 'view-all')); ?>" class="w3-right">View More</a> 	
			</div>
			
			<?php endif; ?>
		</div>
	</div>
	<!-- end middle column -->
</div>
<!-- end page content -->





