<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="UTF-8">

		<title>p-Blah - Register</title>

		<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css" type="text/css">
    	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    	<link rel="stylesheet" href="http://www.w3schools.com/lib/w3-theme-blue-grey.css">
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    	<script src="https://code.jquery.com/jquery-3.1.1.min.js" type="text/javascript"></script>

		<style>
            html, body, h1, h2, h3, h4, h5 {
                font-family: "Open Sans", sans-serif;
            }
        </style>


	</head>

	<body class="w3-theme-15">
		<div class="w3-top">
		<!-- default navbar -->
			<ul class="w3-navbar w3-theme-d2 w3-left-align w3-large">
				<li class="w3-hide-medium w3-hide-large w3-opennav w3-right">
					<a class="w3-padding-large w3-hover-pale-green w3-theme-d2" href="javascript:void(0);"><i class="fa fa-bars"></i></a>
				</li>

				<li><a href="/" class="w3-padding-large w3-theme-d4"><i class="fa fa-home w3-margin-right"></i>Home</a></li>

			</ul>
		</div>


		<div class="w3-container w3-content w3-center" style="max-width: 1400px; margin-top: 80px;">
			<div class="w3-col m12">
				<div class="w3-row-padding">
					<div class="w3-col m12">
						<div class="w3-card-2 w3-round w3-white">
							<div class="w3-container w3-padding">
								<h3 class="w3-opacity">Database Error!</h3>
							</div>
						</div>
					</div>
				</div>

				<div class="w3-container w3-card-2 w3-white w3-round w3-margin">
					<br>

					<h4 class="w3-center">Oops! A database error has occurred.</h4>

					<br>

					<hr class="w3-clear">

					<p><?php echo $this->content; ?></p>
				</div>
			</div>
		</div>
	</body>
</html>