<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="UTF-8">
		<title>p-Blah Setup</title>

		<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css" type="text/css">
    	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    	<link rel="stylesheet" href="http://www.w3schools.com/lib/w3-theme-blue-grey.css">
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    	<script src="https://code.jquery.com/jquery-3.1.1.min.js" type="text/javascript"></script>

		<style>
            html, body, h1, h2, h3, h4, h5 {
            	font-family: "Open Sans", sans-serif;
            }
        </style>


	</head>

	<body class="w3-theme-15">
		<div class="w3-top">
 			<ul class="w3-navbar w3-theme-d2 w3-left-align w3-large">
  				<li class="w3-hide-medium w3-hide-large w3-opennav w3-right">
    				<a class="w3-padding-large w3-hover-pale-green w3-large w3-theme-d2" href="javascript:void(0);">
    				<i class="fa fa-bars"></i></a>
  				</li>

  				<li><a href="#" class="w3-padding-large w3-theme-d4"><i class="fa fa-home w3-margin-right"></i>p-Blah</a></li>
		 	</ul>
		</div>

		<div class="w3-container w3-content w3-center" style="max-width: 1400px; margin-top: 80px;">
			<div class="w3-col m12">

				<!-- setup form -->
				<div class="w3-container w3-card-2 w3-white w3-round w3-margin">
					<div class="step-2-holder">

						<p id="setup-form-text">Fill out the following form with your desired username and password to complete the setup.</p>



						<?php echo $this->content; ?>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>