<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="UTF-8">

		<title>p-Blah - Verify</title>

		<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css" type="text/css">
    	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    	<link rel="stylesheet" href="http://www.w3schools.com/lib/w3-theme-blue-grey.css">
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    	<script src="https://code.jquery.com/jquery-3.1.1.min.js" type="text/javascript"></script>

		<style>
            html, body, h1, h2, h3, h4, h5 {
                font-family: "Open Sans", sans-serif;
            }
        </style>


	</head>

	<body class="w3-theme-15">
		<div class="w3-top">
		<!-- default navbar -->
			<ul class="w3-navbar w3-theme-d2 w3-left-align w3-large">
				<li class="w3-hide-medium w3-hide-large w3-opennav w3-right">
					<a class="w3-padding-large w3-hover-pale-green w3-theme-d2" href="javascript:void(0);" id="open-nav"><i class="fa fa-bars"></i></a>
				</li>

				<li><a href="<?php echo $this->url('home', array('action' => 'index')); ?>" class="w3-padding-large w3-theme-d4"><i class="fa fa-home w3-margin-right"></i>Home</a></li>
				<li class="w3-hide-small"><a href="<?php echo $this->url('home/member-login', array('action' => 'index')); ?>" class="w3-padding-large w3-hover-pale-green" title="Member Login"><i class="fa fa-user"></i></a></li>
				<li class="w3-hide-small"><a href="<?php echo $this->url('home/admin-login', array('action' => 'index')); ?>" class="w3-padding-large w3-hover-pale-green" title="Admin Login"><i class="fa fa-adn"></i></a></li>
				<li class="w3-hide-small"><a href="<?php echo $this->url('home/forum', array('action' => 'index')); ?>" class="w3-padding-large w3-hover-pale-green" title="Forums"><i class="fa fa-group"></i></a></li>
			</ul>
		</div>

		<!-- small screens -->
		<div id="small-nav" class="w3-hide w3-hide-large w3-hide-medium w3-top" style="margin-top: 51px;">
			<ul class="w3-navbar w3-left-align w3-large w3-theme">
				<li><a class="w3-padding-large" href="<?php echo $this->url('home/member-login', array('action' => 'index')); ?>">Member Login</a></li>
				<li><a class="w3-padding-large" href="<?php echo $this->url('home/admin-login', array('action' => 'index')); ?>">Admin Login</a></li>
				<li><a class="w3-padding-large" href="<?php echo $this->url('home/forum', array('action' => 'index')); ?>">Forums</a></li>
			</ul>
		</div>

		<div class="w3-container w3-content" style="max-width: 1400px; margin-top: 80px;">
			<div class="w3-col m12">

			    <!-- register form -->
				<div class="w3-container w3-card-2 w3-white w3-round w3-margin">
					<?php echo $this->content; ?>
				</div>
			</div>
		</div>


		<script type="text/javascript">
			$('#open-nav').on('click', function() {
				if (!$('#small-nav').hasClass('w3-show')) {
					$('#small-nav').addClass('w3-show');
				} else {
					$('#small-nav').removeClass('w3-show');
				}
			});
        </script>
	</body>
</html>