<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="UTF-8">

	<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css" type="text/css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link rel="stylesheet" href="http://www.w3schools.com/lib/w3-theme-blue-grey.css">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <script src="https://code.jquery.com/jquery-3.1.1.min.js" type="text/javascript"></script>

	<style>
        html, body, h1, h2, h3, h4, h5 {
            font-family: "Open Sans", sans-serif;
        }
    </style>
</head>

<body class="w3-light-grey">
	<div class="w3-content" style="max-width: 1400px">

		<header class="w3-container w3-center w3-padding-32">
			<h1><b>p-Blah</b></h1>
			<p>Simple, powerful forum software</p>
			<?php echo $this->content; ?>
		</header>

		<div class="w3-row-padding">
			<div class="w3-col l8 s12">
				<div class="w3-card-4 w3-margin w3-white">
					<img src="<?php echo $this->basePath(); ?>/images/mars.jpg" alt="Mars" style="width: 100%">
					<div class="w3-container w3-padding-8">
						<h3>
							<b>Mars</b>
						</h3>
						<h5>
							Mars the Red Planet <span class="w3-opacity"><?php echo date('Y-m-d', strtotime("now")); ?></span>
						</h5>
					</div>

					<div class="w3-container">
						<p>Picture I took of Mars</p>
						<div class="w3-row">
							<div class="w3-col m8 s12">
								<p>
									<button class="w3-btn w3-padding-large w3-white w3-border w3-hover-border-black">
										<b>View More.. &raquo;</b>
									</button>
								</p>
							</div>
							<div class="w3-col m4 w3-hide-small">
								<p>
									<span class="w3-padding-large w3-right">
										<b>Comments &nbsp;</b>
										<span class="w3-badge">0</span>
									</span>
								</p>
							</div>
						</div>
					</div>
				</div>

				<hr>

				<div class="w3-card-4 w3-margin w3-white">
					<img src="<?php echo $this->basePath(); ?>/images/marlee.jpg" alt="Marlee" style="width: 100%">
					<div class="w3-container w3-padding-8">
						<h3>
							<b>Marlee</b>
						</h3>
						<h5>
							My niece Marlee <span class="w3-opacity"><?php echo date('Y-m-d', strtotime("now")); ?></span>
						</h5>
					</div>

					<div class="w3-container">
						<p>Picture I took of my awesome niece of Marlee</p>
						<div class="w3-row">
							<div class="w3-col m8 s12">
								<p>
									<button class="w3-btn w3-padding-large w3-white w3-border w3-hover-border-black">
										<b>View More.. &raquo;</b>
									</button>
								</p>
							</div>
							<div class="w3-col m4 w3-hide-small">
								<p>
									<span class="w3-padding-large w3-right">
										<b>Comments &nbsp;</b>
										<span class="w3-badge">0</span>
									</span>
								</p>
							</div>
						</div>
					</div>
				</div>

				<hr>

				<div class="w3-card-4 w3-margin w3-white">
					<img src="<?php echo $this->basePath(); ?>/images/jake.jpg" alt="Jake" style="width: 100%">
					<div class="w3-container w3-padding-8">
						<h3>
							<b>My dog</b>
						</h3>
						<h5>
							Jake <span class="w3-opacity"><?php echo date('Y-m-d', strtotime("now")); ?></span>
						</h5>
					</div>

					<div class="w3-container">
						<p>Picture I took of my dog Jake</p>
						<div class="w3-row">
							<div class="w3-col m8 s12">
								<p>
									<button class="w3-btn w3-padding-large w3-white w3-border w3-hover-border-black">
										<b>View More.. &raquo;</b>
									</button>
								</p>
							</div>
							<div class="w3-col m4 w3-hide-small">
								<p>
									<span class="w3-padding-large w3-right">
										<b>Comments &nbsp;</b>
										<span class="w3-badge">0</span>
									</span>
								</p>
							</div>
						</div>
					</div>
				</div>

				<hr>

				<div class="w3-card-4 w3-margin w3-white">
					<img src="<?php echo $this->basePath(); ?>/images/harry.jpg" alt="Harrison" style="width: 100%">
					<div class="w3-container w3-padding-8">
						<h3>
							<b>Harrison</b>
						</h3>
						<h5>
							My nephew Harrison <span class="w3-opacity"><?php echo date('Y-m-d', strtotime("now")); ?></span>
						</h5>
					</div>

					<div class="w3-container">
						<p>Harrison buddy</p>
						<div class="w3-row">
							<div class="w3-col m8 s12">
								<p>
									<button class="w3-btn w3-padding-large w3-white w3-border w3-hover-border-black">
										<b>View More.. &raquo;</b>
									</button>
								</p>
							</div>
							<div class="w3-col m4 w3-hide-small">
								<p>
									<span class="w3-padding-large w3-right">
										<b>Comments &nbsp;</b>
										<span class="w3-badge">0</span>
									</span>
								</p>
							</div>
						</div>
					</div>
				</div>

				<hr>

				<div class="w3-card-4 w3-margin w3-white">
					<img src="<?php echo $this->basePath(); ?>/images/marlee2.jpg" alt="Marlee" style="width: 100%">
					<div class="w3-container w3-padding-8">
						<h3>
							<b>My Niece</b>
						</h3>
						<h5>
							Marlee as a baby <span class="w3-opacity"><?php echo date('Y-m-d'); ?></span>
						</h5>
					</div>

					<div class="w3-container">
						<p>My awesome niece Marlee.</p>
						<div class="w3-row">
							<div class="w3-col m8 s12">
								<p>
									<button class="w3-btn w3-padding-large w3-white w3-border w3-hover-border-black">
										<b>View more.. &raquo;</b>
									</button>
								</p>
							</div>

							<div class="w3-col m4 w3-hide-small">
								<p>
									<span class="w3-padding-large w3-right">
										<b>Comments &nbsp;</b>
										<span class="w3-badge">0</span>
									</span>
								</p>
							</div>
						</div>
					</div>
				</div>
			</div>


			<div class="w3-col l4">
				<div class="w3-card-2 w3-margin w3-margin-top">
					<img src="<?php echo $this->basePath(); ?>/images/jake.jpg" style="width: 100%">
					<div class="w3-container w3-white">
						<h4>
							<b>Jimmy</b>
						</h4>
						<p>I'm a programmer.</p>
					</div>
				</div>
				<hr>

				<div class="w3-card-2 w3-margin">
					<div class="w3-container w3-padding">
						<h4>Popular Posts</h4>
						<form method="get">
							<input type="text" class="w3-input w3-border w3-round-large" placeholder="Search" name="search" style="width: 60%;" required>
							<button type="submit" style="float: right; margin-top: -40px; padding: 8px; width: 30%;" class="w3-btn w3-white w3-border w3-round-large">Search</button>
						</form>
					</div>

					<ul class="w3-ul w3-hoverable w3-white">
						<li class="w3-padding-16">
							<img src="<?php echo $this->basePath(); ?>/images/jake.jpg" alt="Image" class="w3-left w3-margin-right" style="width: 50px">
							<span class="w3-large">My Dog</span><br>
							<span>Jake</span>
						</li>

						<li class="w3-padding-16">
							<img src="<?php echo $this->basePath(); ?>/images/marlee.jpg" alt="Image" class="w3-left w3-margin-right" style="width: 50px">
							<span class="w3-large">My Niece</span><br>
						    <span>Marlee</span>
						</li>

						<li class="w3-padding-16">
							<img src="<?php echo $this->basePath(); ?>/images/mars.jpg" alt="Image" class="w3-left w3-margin-right" style="width: 50px">
							<span class="w3-large">Mars</span><br>
							<span>Closeup of Mars</span>
						</li>

						<li class="w3-padding-16 w3-hide-medium w3-hide-small">
							<img src="<?php echo $this->basePath(); ?>/images/harry.jpg" alt="Image" class="w3-left w3-margin-right" style="width: 50px">
							<span class="w3-large">My Nephew</span><br>
							<span>Harry</span>
						</li>

						<li class="w3-padding-16 w3-hide-medium w3-hide-small">
							<img src="<?php echo $this->basePath(); ?>/marlee2.jpg" alt="Image" class="w3-left w3-margin-right" style="width: 50px">
							<span class="w3-large">My Niece</span><br>
							<span>Marlee</span>
						</li>
					</ul>
				</div>
				<hr>

			</div>
		</div>
		<br>
	</div>


	<footer class="w3-container w3-blue-grey w3-padding-32 w3-margin-top">
		<p class="w3-center">&copy; <?php echo date('Y'); ?> Jimmy Sole. All Rights Reserved.</p>
	</footer>
</body>
</html>