<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="UTF-8">

	<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css" type="text/css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link rel="stylesheet" href="http://www.w3schools.com/lib/w3-theme-blue-grey.css">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <script src="https://code.jquery.com/jquery-3.1.1.min.js" type="text/javascript"></script>

	<style>
        html, body, h1, h2, h3, h4, h5 {
            font-family: "Open Sans", sans-serif;
        }
    </style>
</head>

<body class="w3-light-grey">
	<div class="w3-content" style="max-width: 1400px">

		<header class="w3-container w3-center w3-padding-32">
			<?php echo $this->content; ?>
		</header>

		<footer class="w3-container w3-blue-grey w3-padding-32 w3-margin-top">
			<p class="w3-center">&copy; <?php echo date('Y'); ?> Jimmy Sole. All Rights Reserved.</p>
		</footer>
	</div>
</body>
</html>