<div class="w3-row">
	<!-- left col -->
	<div class="w3-col m3">
		<!-- group members currently online col (left) -->
		<div class="w3-card-2 w3-round w3-theme-d2">
			<div class="w3-container w3-round w3-theme-d2">
				<h6 class="w3-center" style="border-bottom: 1px solid #ddd;">Group
					Members Online</h6>

				<p id="members-online"></p>

				<script type="text/javascript">
					$(function() {
						 function buildOnlineMemberList() {
							$.ajax({
								type: "GET",
							    url: "/members/groups/get-group-members-online",
							    dataType: "json"
							}).done(function(msg) {
								if (msg.display_name == "" || msg.display_name == undefined) {
									$('#members-online').html("No group members are online.");
									return false;
								} else {
							    	var displayNames = msg.display_name.join('<br />');
							    	$("#members-online").html(displayNames);
								}
							}).fail(function() {
							   	$('#members-online').html("Error retrieving group list.");
							});
						 }

						 setInterval(function() {
						  	buildOnlineMemberList();
						 }, 5000);

					     buildOnlineMemberList();
					});
				</script>
			</div>
		</div>

		<br> <br>
		<div class="w3-card-2 w3-round w3-theme-d2">
			<div class="w3-container w3-round w3-theme-d2">
				<h6 class="w3-center" style="border-bottom: 1px solid #ddd;">Photo
					Options</h6>
				<p class="w3-left">
					<a
						href="<?php echo $this->url('members/profile', array('action' => 'view-photo-albums')); ?>">View
						Photos</a> <br> <a
						href="<?php echo $this->url('members/profile', array('action' => 'edit-photos')); ?>">Edit
						Photos</a> <br> <a
						href="<?php echo $this->url('members/profile', array('action' => 'remove-photos')); ?>">Remove
						Photos</a> <br> <a
						href="<?php echo $this->url('members/profile', array('action' => 'remove-photo-album')); ?>">Remove
						Photo Album</a> <br> <a
						href="<?php echo $this->url('members/profile', array('action' => 'make-photo-album')); ?>">Create
						a Photo Album</a> <br>
				</p>
			</div>
		</div>
	</div>
	<!-- end left col -->

	<!-- mid col -->
	<div class="w3-col m7">
		<div class="w3-row-padding">
			<div class="w3-col m12">
				<div class="w3-card-2 w3-round w3-white">
					<div class="w3-container w3-padding" id="add-photos">
					<?php if (!$this->form): ?>
						<p class="w3-center">You currently have no albums.</p>
					<?php else: ?>
						<p class="w3-center">Add Photos To A Album</p>

						<p>
							<?php
        $this->form->setAttribute('action', $this->url('members/profile', array(
            'action' => 'photos-to-album'
        )));
        
        $this->form->prepare();
        
        echo $this->form()->openTag($this->form);
        ?>
							
							<br>
							
							<?php
        echo $this->formRow($this->form->get('album-name'));
        
        echo "<br>";
        
        echo $this->formRow($this->form->get('copy-from-album'));
        
        echo "<br>";
        
        echo $this->formRow($this->form->get('photos'));
        
        echo $this->formElement($this->form->get('csrf_security'));
        
        echo "<br><br>";
        
        echo $this->formElement($this->form->get('submit'));
        
        echo $this->form()->closeTag();
        
        ?>
						</p>

						<script type="text/javascript">
							$('#album-name').on('blur', function() {
								if ($(this).val() == "" || $(this).val() == undefined) {
									$('#album-name-error').css('display', 'block');
									$(this).focus();
									return;
								}

								if ($(this).val().length < 10 || $(this).val().length > 100) {
									$('#album-size-error').css('display', 'block');
									$(this).focus();
									return;
								}
							});

							$('#submit').on('click', function(e) {
								if ($('#album-name').val() == "" || $('#album-name').val() == undefined) {
									e.preventDefault();
									$('#album-name-error').css('display', 'block');
									$('#album-name').focus();
									return;
								}

								if ($('#album-name').val().length < 10 || $('#album-name').val().length > 100) {
									e.preventDefault();
									$('#album-size-error').css('display', 'block');
									$('#album-name').focus();
									return;
								}
							}); 
						</script>
					<?php endif; ?>
				</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end mid col -->
</div>