<div class="w3-row">
	<!-- left col -->
	<div class="w3-col m3">
		<!-- group members currently online col (left) -->
		<div class="w3-card-2 w3-round w3-theme-d2">
			<div class="w3-container w3-round w3-theme-d2">
				<h6 class="w3-center" style="border-bottom: 1px solid #ddd;">Group
					Members Online</h6>

				<p id="members-online"></p>
				
				<script type="text/javascript">
					$(function() {
						 function buildOnlineMemberList() {
							$.ajax({
								type: "GET",
							    url: "/members/groups/get-group-members-online",
							    dataType: "json"
							}).done(function(msg) {
								if (msg.display_name == "" || msg.display_name == undefined) {
									$('#members-online').html("No group members are online.");
									return false;
								} else {
							    	var displayNames = msg.display_name.join('<br />');
							    	$("#members-online").html(displayNames);
								}
							}).fail(function() {
							   	$('#members-online').html("Error retrieving group list.");
							});
						 }

						 setInterval(function() {
						  	buildOnlineMemberList();
						 }, 5000);

					     buildOnlineMemberList();
					});
				</script>
			</div>
		</div>

		<br> <br>
		<div class="w3-card-2 w3-round w3-theme-d2">
			<div class="w3-container w3-round w3-theme-d2">
				<h6 class="w3-center" style="border-bottom: 1px solid #ddd;">Photo
					Options</h6>
				<p class="w3-left">
					<a
						href="<?php echo $this->url('members/profile', array('action' => 'view-photo-albums')); ?>">View
						Photos</a> <br> <a
						href="<?php echo $this->url('members/profile', array('action' => 'edit-photos')); ?>">Edit
						Photos</a> <br> <a
						href="<?php echo $this->url('members/profile', array('action' => 'remove-photos')); ?>">Remove
						Photos</a> <br> <a
						href="<?php echo $this->url('members/profile', array('action' => 'remove-photo-album')); ?>">Remove
						Photo Album</a> <br> <a
						href="<?php echo $this->url('members/profile', array('action' => 'make-photo-album')); ?>">Create
						a Photo Album</a> <br>
				</p>
			</div>
		</div>
	</div>
	<!-- end left col -->

	<!-- mid col -->
	<div class="w3-col m7">
		<div class="w3-row-padding">
			<div class="w3-col m12">
				<div class="w3-card-2 w3-round w3-white">
					<div class="w3-container w3-padding" id="add-photos">
					<?php if (!$this->form): ?>
						<p class="w3-center">You currently have no albums.</p>
					<?php else: ?>
						<p class="w3-center">Remove Photos From A Album</p>

						<p>
							<?php
        $this->form->setAttribute('action', $this->url('members/profile', array(
            'action' => 'photos-gone-album'
        )));
        
        $this->form->prepare();
        
        echo $this->form()->openTag($this->form);
        ?>
							
							<br>
							
							<?php
        echo $this->formRow($this->form->get('album-name'));
        
        echo $this->formElement($this->form->get('csrf_security'));
        
        ?>
						</p>
						<br>

						<div class="w3-container" id="album-header" style="display: none;">
							<h4 class="w3-text-black"></h4>
						</div>
						
						<div class="w3-row-padding w3-margin-top" style="display: none;"></div>
						
						<div class="w3-row" id="no-album-photos">
							<div class="w3-col m12" style="display: none;"></div>
						</div>
						
						<script type="text/javascript">
							$('#album-name').on('change', function() {
								// retrieve the images from the photo album selected
								$.ajax({
									type: "POST",
									url: "/members/profile/get-photos-from-album",
									dataType: "json",
									data:  { 
										album_name: $('#album-name option:selected').val()
									}
								}).done(function(msg) {
									if (msg.photos == undefined) {
										$('#no-album-photos .w3-col m12').attr('style', 'display: initial;');
										$('#no-album-photos .w3-col m12 ').html("<p>No photos were found in the album</p>");

										return false;
									} else {
										if ($('.w3-row-padding .w3-margin-top img').length > 0) {
											// remove previous images
											$('.w3-row-padding .w3-margin-top').empty();
										}
										$('#album-header').attr('style', 'display: initial;');

										$('#album-header h4').html("Photos in " + $('#album-name option:selected').text().split("_")[0] + ":");

										$('.w3-row-padding .w3-margin-top').attr('style', 'display: initial;');

										
										$.each(msg.photos, function(i, item) {
											$('.w3-row-padding .w3-margin-top').append('<div class="w3-third" style="width: 32.5%; max-height: 200px;"><div class="w3-card-2 w3-margin"><img src="<?php echo $this->basePath() . '/images/profile/' . $this->identity() . '/albums/'; ?>' + $('#album-name option:selected').val() + '/' + msg.photos[i] + '" style="width:100%; max-height: 150px; padding-bottom: 5px;"></div><br></div>');
										});
									}
								}).fail(function(msg) {
									alert(msg);
								});
							});
						</script>
						<br><br>
		<?php
		    echo $this->formElement($this->form->get('submit'));
        
		    echo $this->form()->closeTag();
        ?>
					<?php endif; ?>
				</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end mid col -->
</div>
