<div class="w3-row">
	<!-- left col -->
	<div class="w3-col m3">
		<!-- group members currently online col (left) -->
		<div class="w3-card-2 w3-round w3-theme-d2">
			<div class="w3-container w3-round w3-theme-d2">
				<h6 class="w3-center" style="border-bottom: 1px solid #ddd;">Group
					Members Online</h6>

				<p id="members-online"></p>
				
				<script type="text/javascript">
					$(function() {
						 function buildOnlineMemberList() {
							$.ajax({
								type: "GET",
							    url: "/members/groups/get-group-members-online",
							    dataType: "json"
							}).done(function(msg) {
								if (msg.display_name == "" || msg.display_name == undefined) {
									$('#members-online').html("No group members are online.");
									return false;
								} else {
							    	var displayNames = msg.display_name.join('<br />');
							    	$("#members-online").html(displayNames);
								}
							}).fail(function() {
							   	$('#members-online').html("Error retrieving group list.");
							});
						 }

						 setInterval(function() {
						  	buildOnlineMemberList();
						 }, 5000);

					     buildOnlineMemberList();
					});
				</script>
			</div>
		</div>

		<br> <br>
		<div class="w3-card-2 w3-round w3-theme-d2">
			<div class="w3-container w3-round w3-theme-d2">
				<h6 class="w3-center" style="border-bottom: 1px solid #ddd;">Photo
					Options</h6>
				<p class="w3-left">
					<a
						href="<?php echo $this->url('members/profile', array('action' => 'view-photo-albums')); ?>">View
						Photos</a> <br> <a
						href="<?php echo $this->url('members/profile', array('action' => 'edit-photos')); ?>">Edit
						Photos</a> <br> <a
						href="<?php echo $this->url('members/profile', array('action' => 'remove-photos')); ?>">Remove
						Photos</a> <br> <a
						href="<?php echo $this->url('members/profile', array('action' => 'remove-photo-album')); ?>">Remove
						Photo Album</a> <br> <a
						href="<?php echo $this->url('members/profile', array('action' => 'make-photo-album')); ?>">Create
						a Photo Album</a> <br>
				</p>
			</div>
		</div>
	</div>
	<!-- end left col -->

	<!-- mid col -->
	<div class="w3-col m7" id="refresh-div">
		<div class="w3-row-padding">
			<div class="w3-col m12">
				<div class="w3-card-2 w3-round w3-white">
					<div class="w3-container w3-padding" id="add-photos">
					<?php if (!$this->form): ?>
						<p class="w3-center">You currently have no albums.</p>
					<?php else: ?>
						<p class="w3-center">Remove Photos From A Album</p>

						<p>
							<?php
        $this->form->setAttribute('action', $this->url('members/profile', array(
            'action' => 'handle-photo-delete'
        )));
        
        $this->form->prepare();
        
        echo $this->form()->openTag($this->form);
        ?>
							
							<br>
							
							<?php
        echo $this->formRow($this->form->get('album-name'));
        
        echo $this->formElement($this->form->get('csrf_security'));
        
        ?>
						</p>
						<br>

						<div class="w3-container" id="album-header" style="display: none;">
							<h4 class="w3-text-black"></h4>
						</div>
						
						<div class="w3-row-padding w3-margin-top" style="display: none;"></div>
						
						<div class="w3-row" id="no-album-photos">
							<div class="w3-col m12" style="display: none;"></div>
						</div>
						
						<script type="text/javascript">
							var post_params;
						
							$('#album-name').on('change', function() {
								// retrieve the images from the photo album selected
								if ($('#album-name option:selected').val() == "") {
									alert("Please choose a valid album.");
									return false;
								}
								
								$.ajax({
									type: "POST",
									url: "/members/profile/get-photos-from-album",
									dataType: "json",
									data: { 
										album_name: $('#album-name option:selected').val()
									}
								}).done(function(msg) {
									if (msg.photos == undefined || msg.photos == null || msg.photos == "") {
										$('#no-album-photos, .w3-col m12').attr('style', 'display: initial;');
										$('#no-album-photos, .w3-col m12').html("<p>No photos were found in the album " +  $('#album-name option:selected').val() + "</p>");

										return false;
									} else {
										if ($('.w3-row-padding .w3-margin-top img').length > 0) {
											// remove previous images
											$('.w3-row-padding .w3-margin-top').empty();
										}

										$('#check-all').attr('style', 'display: initial;');
										$('#uncheck-all').attr('style', 'display: initial;');
										
										$('#album-header').attr('style', 'display: initial;');

										$('#album-header h4').html("Photos in " + $('#album-name option:selected').text().split("_")[0] + ":");

										$('.w3-row-padding .w3-margin-top').attr('style', 'display: initial;');

										
										$.each(msg.photos, function(i, item) {
											$('.w3-row-padding .w3-margin-top').append('<div class="w3-third" style="width: 32.5%; max-height: 200px;"><div class="w3-card-2 w3-margin"><img class="photo" src="<?php echo $this->basePath() . '/images/profile/' . $this->identity() . '/albums/'; ?>' 
											+ $('#album-name option:selected').val() + '/' + msg.photos[i] + '" style="width: 100%; max-height: 150px; padding-bottom: 5px;">' +
											'<input class="w3-check" type="checkbox" name="delete_' + msg.photos[i] + '" id="delete_' + msg.photos[i] + '">' +
											'<label for="delete_' + msg.photos[i] + '">&nbsp;Check to Delete</label></div><br></div>');
									    });

									    
										$('.w3-check').on('change', function() {
											var array = [];

											$('.w3-card-2.w3-margin input.w3-check:checked').each(function(index, checkbox) {
												var $checkbox = $(checkbox);

												var $card = $checkbox.closest('.w3-card-2.w3-margin');

												var $img = $card.find('img.photo');

												array[array.length] = /[^/]*$/.exec($img.attr('src'))[0];
											});

											post_params = array;
										});  
										

										$('#check_all').on('click', function() {
											$('.w3-check').each(function() {
												if ($(this).is(':not(:checked)')) {
													$(this).attr('checked', 'checked');
													$("label[for='" + $(this).attr("name")  + "']").html("&nbsp;Selected to delete");
													$('#uncheck_all').attr('disabled', false);

													var values = $('img.photo');

													var map = values.map(function() {
														return /[^/]*$/.exec($(this).attr('src'))[0];
													}).get();
													
													post_params = map;
												} else {
													alert("All items are already checked.");
													$('#check_all').attr('disabled', true);
													return false;
												}
											});
										});

										$('#uncheck_all').on('click', function() {
											$('.w3-check').each(function() {
												if ($(this).is(':checked')) {
													$(this).attr('checked', false);
													$("label[for='" + $(this).attr("name")  + "']").html("&nbsp;Check to delete");
													$('#check_all').attr('disabled', false);
												} else {
													alert("No items are checked");
													$('#uncheck_all').attr('disabled', true);
													return false;
												}
											});
										});
									}
								}).fail(function(msg) {
									alert(msg);
								});
							});
						</script>
						<br><br>
						<div class="w3-left" style="display: none;" id="check-all"><button class="w3-btn w3-white w3-border w3-border-blue w3-round" id="check_all" type="button">Check All</button></div>
						&nbsp;&nbsp;
						<div class="w3-center" style="display: none;" id="uncheck-all"><button class="w3-btn w3-white w3-border w3-border-blue w3-round" id="uncheck_all" type="button">Uncheck All</button></div>
		<?php
		    echo $this->formElement($this->form->get('submit'));
        
		    echo $this->form()->closeTag();
        ?>
        			<script type="text/javascript">
						$('#submit').on('click', function(e) {
							e.preventDefault();

							if (confirm("Are you sure you want to delete these photos?")) {
								$.post('/members/profile/handle-photo-delete', { album: $('#album-name').val(), images: post_params })
									.done(function(msg) {
										alert(msg);
									    location.reload(true);
									}).fail(function(msg) {
										alert(msg);
									});
							}
						});
        			</script>
					<?php endif; ?>
				</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end mid col -->
</div>
