<div class="w3-row">
	<!-- left col -->
	<div class="w3-col m3">
		<!-- group members currently online col (left) -->
		<div class="w3-card-2 w3-round w3-theme-d2">
			<div class="w3-container w3-round w3-theme-d2">
				<h6 class="w3-center" style="border-bottom: 1px solid #ddd;">Group
					Members Online</h6>

				<p id="members-online"></p>

				<script type="text/javascript">
					$(function() {
						 function buildOnlineMemberList() {
							$.ajax({
								type: "GET",
							    url: "/members/groups/get-group-members-online",
							    dataType: "json"
							}).done(function(msg) {
								if (msg.display_name == "" || msg.display_name == undefined) {
									$('#members-online').html("No group members are online.");
									return false;
								} else {
							    	var displayNames = msg.display_name.join('<br />');
							    	$("#members-online").html(displayNames);
								}
							}).fail(function() {
							   	$('#members-online').html("Error retrieving group list.");
							});
						 }

						 setInterval(function() {
						  	buildOnlineMemberList();
						 }, 5000);

					     buildOnlineMemberList();
					});
				</script>
			</div>
		</div>

		<br> <br>
		<div class="w3-card-2 w3-round w3-theme-d2">
			<div class="w3-container w3-round w3-theme-d2">
				<h6 class="w3-center" style="border-bottom: 1px solid #ddd;">Photo
					Options</h6>
				<p class="w3-left">
					<a
						href="<?php echo $this->url('members/profile', array('action' => 'add-photos')); ?>">Add
						Photos</a> <br> 
					<a
						href="<?php echo $this->url('members/profile', array('action' => 'edit-photos')); ?>">Edit
						Photos</a> <br> 
					<a
						href="<?php echo $this->url('members/profile', array('action' => 'remove-photos')); ?>">Remove
						Photos</a> <br>
						
					<a 
						href="<?php echo $this->url('members/profile', array('action' => 'remove-photo-album')); ?>">Remove 
						Photo Album</a> <br>
						
					<a
						href="<?php echo $this->url('members/profile', array('action' => 'make-photo-album')); ?>">Create
						a Photo Album</a> <br>
				</p>
			</div>
		</div>
	</div>
<!-- end left col -->

<!-- mid col -->
<div class="w3-col m7">
	<div class="w3-row-padding">
		<div class="w3-col m12">
			<div class="w3-card-2 w3-round w3-white">
				<div class="w3-container w3-padding" id="view-photo-albums">
				 <?php if (count($this->photo_albums, 1) < 1): ?>
					   	   <p class="w3-center">You currently have no albums.</p>
					   <?php else: ?>
					<p class="w3-center">Current Albums</p>
					<br>
						<div class="w3-responsive w3-padding">
								<table class="w3-table-all">
									<tr>
										<th>Album Name</th>
										<th>Created Date</th>
										<th># of Photos</th>
									</tr>
								
								<?php
        $i = 1;
        foreach ($this->files as $album_name => $list_files):
            
            ?>
							
								<tr>
									<td id="aid_<?php echo $i++; ?>"><?php echo strstr($album_name, '_', true); ?></td>
									<td><?php echo substr(strrchr($album_name, "_"), 1); ?></td>
									<td><?php echo count($list_files);?></td>

								</tr>
								
								<?php endforeach; ?>
							</table>
						</div>
					</div>
					<?php endif; ?>
			</div>
		</div>
	</div>
</div>
<!-- end mid col -->
</div>