<div class="w3-container">
	<div class="w3-row-padding">
		<div class="w3-col m12">
			<h4 class="w3-center">Upload Files</h4>
			<div class="w3-center" id="multiplefileuploader">Upload</div>
			<div class="w3-center" id="status"></div>
		</div>
		
		<br class="w3-clear">
		
		<div class="w3-col m12">
			<button onclick="back()">Back</button>
			
			<script type="text/javascript">
				function back() {
					window.location = '/members/profile';
				}
			</script>
		</div>
	</div>
</div>